@tech-items-api = https://kk5tvwvjwb.execute-api.us-east-2.amazonaws.com

### LIST TECH ITEMS
GET {{tech-items-api}}/tech-items

### CREATE TECH ITEM
POST {{tech-items-api}}/tech-items HTTP/1.1
Content-Type: application/json

{
  "priority": 100,
  "description": "Update it to tried"
}

### GET TECH ITEM
GET {{tech-items-api}}/tech-items/1619991573315

### DELETE TECH ITEM
DELETE {{tech-items-api}}/tech-items/1619991573315

### UPDATE TECH ITEM
PUT {{tech-items-api}}/tech-items/1619991573315 HTTP/1.1
Content-Type: application/json

{
  "tried": true
}
