@tech-items-api = https://kk5tvwvjwb.execute-api.us-east-2.amazonaws.com

### LIST TECH ITEMS
GET {{tech-items-api}}/tech-items

### CREATE TECH ITEM: success
POST {{tech-items-api}}/tech-items HTTP/1.1
Content-Type: application/json

{
  "priority": 10,
  "description": "Sample item from VS awesome Rest Client"
}

### CREATE TECH ITEM: missing field
POST {{tech-items-api}}/tech-items HTTP/1.1
Content-Type: application/json

{
  "priority": 10,
  "name": "Wrong field name"
}
